# Generated by Django 5.2.7 on 2025-11-01 06:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('especialidad', models.CharField(help_text='Especialidad médica (Cardiología, Pediatría, etc.)', max_length=100)),
                ('sub_especialidad', models.CharField(blank=True, help_text='Sub-especialidad si aplica', max_length=100)),
                ('cedula_profesional', models.CharField(help_text='Cédula profesional', max_length=50, unique=True)),
                ('cedula_especialidad', models.CharField(blank=True, help_text='Cédula de especialidad', max_length=50)),
                ('universidad', models.CharField(blank=True, max_length=200)),
                ('anos_experiencia', models.IntegerField(help_text='Años de experiencia', validators=[django.core.validators.MinValueValidator(0)])),
                ('biografia', models.TextField(blank=True, help_text='Biografía profesional del médico')),
                ('activo', models.BooleanField(default=True, help_text='Si el médico está activo para consultas')),
                ('acepta_nuevos_pacientes', models.BooleanField(default=True)),
                ('duracion_consulta_minutos', models.IntegerField(default=30, help_text='Duración estándar de consulta en minutos', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)])),
                ('costo_consulta', models.DecimalField(decimal_places=2, help_text='Costo de la consulta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['apellido_paterno', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(blank=True, help_text='Médico que realiza la consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='medical.medico'),
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de atención')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de atención')),
                ('activo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='medical.medico')),
            ],
            options={
                'verbose_name': 'Horario Médico',
                'verbose_name_plural': 'Horarios Médicos',
                'ordering': ['medico', 'dia_semana', 'hora_inicio'],
                'unique_together': {('medico', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de la cita')),
                ('duracion_minutos', models.IntegerField(help_text='Duración estimada en minutos', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)])),
                ('tipo_consulta', models.CharField(choices=[('primera_vez', 'Primera Vez'), ('seguimiento', 'Seguimiento'), ('urgencia', 'Urgencia'), ('control', 'Control')], default='primera_vez', max_length=20)),
                ('motivo', models.TextField(help_text='Motivo de la cita')),
                ('notas_paciente', models.TextField(blank=True, help_text='Notas adicionales del paciente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada_paciente', 'Cancelada por Paciente'), ('cancelada_medico', 'Cancelada por Médico'), ('no_asistio', 'Paciente no asistió')], default='pendiente', max_length=30)),
                ('confirmada_por_paciente', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('fecha_recordatorio', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consulta', models.OneToOneField(blank=True, help_text='Consulta asociada una vez realizada la cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita', to='medical.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='medical.paciente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='medical.medico')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora', 'medico'], name='medical_cit_fecha_h_9009c3_idx'), models.Index(fields=['paciente', 'estado'], name='medical_cit_pacient_57efa8_idx')],
            },
        ),
    ]
