# Generated by Django 5.1.2 on 2025-11-05 21:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_medico_consulta_medico_horariomedico_cita'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cita',
            name='medical_cit_fecha_h_9009c3_idx',
        ),
        migrations.AddField(
            model_name='cita',
            name='consultorio',
            field=models.CharField(blank=True, help_text='Número o nombre del consultorio', max_length=50),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 11, 5), help_text='Fecha de la cita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=datetime.time(21, 7, 42, 646946), help_text='Hora de la cita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='sintomas_iniciales',
            field=models.TextField(blank=True, help_text='Síntomas mencionados en el chat'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion_minutos',
            field=models.IntegerField(default=30, help_text='Duración estimada en minutos', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='AGENDADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(help_text='Email único del paciente', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(help_text='Teléfono de contacto del paciente', max_length=20),
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_hora',
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('medico', 'fecha', 'hora')},
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'hora', 'medico'], name='medical_cit_fecha_24d80c_idx'),
        ),
    ]
